[alembic]
script_location = alembic

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s

# sqlalchemy.url is read from the environment in alembic/env.py
# but a placeholder is helpful for some tools
sqlalchemy.url = driver://user:pass@localhost/dbname
